// src/commands/review/scope.js
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const TEST_DIRS = new Set(['tests', 'benches', 'fuzz']);
const FIXTURE_DIRS = new Set(['fixtures', 'testdata', 'snapshots']);
const FIXTURE_EXTS = new Set(['.snap', '.golden', '.bin']);
const DATA_EXTS = new Set(['.json', '.toml', '.yaml']);
const CFG_TEST_RE = /^\s*#\[cfg\(test\)\]/;
const LOCKFILES = new Set(['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock', 'Cargo.lock', 'pubspec.lock', 'bun.lockb', 'poetry.lock']);
const GENERATED_RE = /@generated|GENERATED CODE|DO NOT (EDIT|MODIFY)|Code generated by|AUTO-GENERATED/i;
const HUNK_RE = /^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/;

function git(cwd, args) {
  try {
    return execSync(`git ${args}`, {
      cwd,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    });
  } catch {
    return null;
  }
}

function getChangedFiles(cwd, base) {
  const out = git(cwd, `diff --name-only ${base}`);
  return out ? out.split('\n').map(s => s.trim()).filter(Boolean) : [];
}

function toLimit(value, fallback) {
  if (typeof value === 'number') return value;
  const parsed = parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function segmentsOf(file) {
  return file.split('/').filter(Boolean);
}

function dirSegmentsOf(file) {
  return segmentsOf(file).slice(0, -1);
}

function extOf(file) {
  return path.posix.extname(file).toLowerCase();
}

function isFixtureFile(file) {
  const ext = extOf(file);
  if (FIXTURE_EXTS.has(ext)) return true;
  const dirs = dirSegmentsOf(file);
  if (dirs.some(d => FIXTURE_DIRS.has(d))) return true;
  if (DATA_EXTS.has(ext) && dirs.some(d => d === 'tests' || d === 'fixtures')) return true;
  return false;
}

function isTestFile(file) {
  if (dirSegmentsOf(file).some(d => TEST_DIRS.has(d))) return true;
  const name = segmentsOf(file).pop();
  return /(^|_)tests?\.rs$/.test(name) || /_test\.dart$/.test(name) || /\.test\.[^.]+$/.test(name) || /\.spec\.[^.]+$/.test(name);
}

function firstCfgTestLine(content) {
  if (content === null) return null;
  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    if (CFG_TEST_RE.test(lines[i])) return i + 1;
  }
  return null;
}

function readNewContent(cwd, file) {
  try {
    return fs.readFileSync(path.join(cwd, file), 'utf8');
  } catch {
    return null;
  }
}

function readOldContent(cwd, base, file) {
  const out = git(cwd, `show ${base}:${JSON.stringify(file)}`);
  return out;
}

// Returns per-line classifiers for one path: added lines use the new file,
// removed lines use the old file (both at their own line numbers).
function classifierFor(cwd, base, file) {
  if (isFixtureFile(file)) {
    return { added: () => 'fixture', removed: () => 'fixture' };
  }
  if (isTestFile(file)) {
    return { added: () => 'test', removed: () => 'test' };
  }
  if (extOf(file) === '.rs') {
    const newStart = firstCfgTestLine(readNewContent(cwd, file));
    let oldStart;
    let oldResolved = false;
    return {
      added: n => (newStart !== null && n >= newStart ? 'test' : 'nonTest'),
      removed: n => {
        if (!oldResolved) {
          oldStart = firstCfgTestLine(readOldContent(cwd, base, file));
          oldResolved = true;
        }
        return oldStart !== null && n >= oldStart ? 'test' : 'nonTest';
      }
    };
  }
  return { added: () => 'nonTest', removed: () => 'nonTest' };
}

// A file whose change is exactly "the formatter was applied to the base version"
// is mechanical: it does not count toward the size limits. The base version is
// formatted next to the real file so the package's formatter config applies.
function formatBaseVersion(cwd, file, oldContent) {
  const ext = extOf(file);
  const dir = path.join(cwd, path.dirname(file));
  if (ext === '.rs') {
    try {
      return execSync('rustfmt --emit stdout --edition 2021', {
        cwd: dir, input: oldContent, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe']
      });
    } catch {
      return null;
    }
  }
  if (ext === '.dart') {
    const tmp = path.join(dir, `preflight_fmt_tmp_${process.pid}_${Date.now()}.dart`);
    try {
      fs.writeFileSync(tmp, oldContent);
      execSync(`dart format ${JSON.stringify(tmp)}`, { cwd: dir, stdio: ['pipe', 'pipe', 'pipe'] });
      return fs.readFileSync(tmp, 'utf8');
    } catch {
      return null;
    } finally {
      try { fs.unlinkSync(tmp); } catch {}
    }
  }
  return null;
}

export function formatterOnlyFiles(cwd, base, files) {
  const exempt = new Set();
  for (const file of files) {
    if (!['.rs', '.dart'].includes(extOf(file))) continue;
    const oldContent = readOldContent(cwd, base, file);
    const newContent = readNewContent(cwd, file);
    if (oldContent === null || newContent === null || oldContent === newContent) continue;
    if (formatBaseVersion(cwd, file, oldContent) === newContent) exempt.add(file);
  }
  return exempt;
}

function stripDiffPrefix(p) {
  return p.replace(/^[ab]\//, '');
}

function countChangedLines(cwd, base, exempt = new Set()) {
  const counts = { nonTest: 0, test: 0, fixture: 0 };
  const diff = git(cwd, `diff -U0 ${base}`);
  if (diff === null) return counts;

  let classifier = { added: () => 'nonTest', removed: () => 'nonTest' };
  let oldFile = null;
  let newFile = null;
  let newLine = 0;
  let oldLine = 0;
  let inHunk = false;

  for (const line of diff.split('\n')) {
    if (line.startsWith('diff --git ')) {
      classifier = { added: () => 'nonTest', removed: () => 'nonTest' };
      oldFile = null;
      newFile = null;
      inHunk = false;
      continue;
    }
    if (line.startsWith('--- ')) {
      const p = line.slice(4).trim();
      oldFile = p === '/dev/null' ? null : stripDiffPrefix(p);
      continue;
    }
    if (line.startsWith('+++ ')) {
      const p = line.slice(4).trim();
      newFile = p === '/dev/null' ? null : stripDiffPrefix(p);
      classifier = classifierFor(cwd, base, newFile || oldFile);
      if (exempt.has(newFile || oldFile)) classifier = null;
      continue;
    }
    const hunk = HUNK_RE.exec(line);
    if (hunk) {
      oldLine = parseInt(hunk[1], 10);
      newLine = parseInt(hunk[2], 10);
      inHunk = true;
      continue;
    }
    if (!inHunk || classifier === null) continue;
    if (line.startsWith('+')) {
      counts[classifier.added(newLine)]++;
      newLine++;
    } else if (line.startsWith('-')) {
      counts[classifier.removed(oldLine)]++;
      oldLine++;
    } else if (line.startsWith(' ')) {
      newLine++;
      oldLine++;
    } else if (line.startsWith('\\')) {
      continue;
    } else {
      inHunk = false;
    }
  }

  return counts;
}

export async function checkScope({
  cwd = process.cwd(),
  base = 'origin/main',
  issueFiles,
  maxLines = 400,
  maxTestLines = 800,
  maxFixtureLines = 50,
  gitDiffFiles
} = {}) {
  const findings = [];
  const changed = gitDiffFiles || getChangedFiles(cwd, base);

  // 1. Issue files check (if provided)
  if (issueFiles) {
    const rawList = Array.isArray(issueFiles) ? issueFiles : issueFiles.split(',');
    const allowed = new Set(rawList.map(s => s.trim()).filter(Boolean));

    for (const f of changed) {
      if (!allowed.has(f)) {
        findings.push({
          check: 'scope',
          severity: 'blocking',
          file: f,
          line: 1,
          message: `Changed file '${f}' is not in --issue-files allowlist`
        });
      }
    }
  }

  // 2. Max lines check — separate limits for non-test, test and fixture lines
  // Per-task exception (recorded in the issue): SWAL_MAX_LINES / SWAL_MAX_TEST_LINES override the defaults.
  const limits = {
    nonTest: toLimit(process.env.SWAL_MAX_LINES || maxLines, 400),
    test: toLimit(process.env.SWAL_MAX_TEST_LINES || maxTestLines, 800),
    fixture: toLimit(maxFixtureLines, 50)
  };
  const exempt = formatterOnlyFiles(cwd, base, changed);
  // Lockfiles are machine-generated from the manifest (which is counted); never review-sized.
  for (const f of changed) if (LOCKFILES.has(path.posix.basename(f))) exempt.add(f);
  // Code generators (flutter_rust_bridge, protoc, build_runner, ...) mark their output in the header.
  for (const f of changed) {
    const head = (readNewContent(cwd, f) || '').split('\n').slice(0, 5).join('\n');
    if (GENERATED_RE.test(head)) exempt.add(f);
  }
  const counts = countChangedLines(cwd, base, exempt);
  const message =
    `Changed lines: non-test ${counts.nonTest}/${limits.nonTest}, ` +
    `test ${counts.test}/${limits.test}, ` +
    `fixture ${counts.fixture}/${limits.fixture}` +
    (exempt.size ? ` (formatter-only, lockfile or generated, not counted: ${[...exempt].join(', ')})` : '');

  const exceeded = [
    { limit: 'maxLines', kind: 'nonTest' },
    { limit: 'maxTestLines', kind: 'test' },
    { limit: 'maxFixtureLines', kind: 'fixture' }
  ].filter(({ kind }) => counts[kind] > limits[kind]);

  for (const { limit } of exceeded) {
    findings.push({
      check: 'scope',
      severity: 'blocking',
      file: 'git-diff',
      line: 1,
      limit,
      message
    });
  }

  return findings;
}
